databases:
  - name: micronaut
    databaseName: micronaut_qzj2
    user: micronaut_qzj2_user

services:
  - type: web
    name: ash
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false