default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234567890
  host: localhost
  port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: budget_app_production
  pool: 5
  username: postgres
  password: 1234567890
